// Code generated by goctl. DO NOT EDIT!
// Source: demo.proto

package server

import (
	"context"

	"lanshan/Courseware-Backend-Go-2022/class15/demo/rpc/internal/logic"
	"lanshan/Courseware-Backend-Go-2022/class15/demo/rpc/internal/svc"
	"lanshan/Courseware-Backend-Go-2022/class15/demo/rpc/pb"
)

type DemoServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedDemoServer
}

func NewDemoServer(svcCtx *svc.ServiceContext) *DemoServer {
	return &DemoServer{
		svcCtx: svcCtx,
	}
}

func (s *DemoServer) SayWorld(ctx context.Context, in *pb.SayWorldReq) (*pb.SayWorldResp, error) {
	l := logic.NewSayWorldLogic(ctx, s.svcCtx)
	return l.SayWorld(in)
}
